definitions:
  helper.Meta:
    properties:
      code:
        description: HTTP status code
        type: integer
      message:
        description: Descriptive message
        type: string
      status:
        description: Status (e.g., "Success", "Failed")
        type: string
    type: object
  helper.Response:
    properties:
      data:
        description: Data holds the actual response data (could be of any type).
      meta:
        $ref: '#/definitions/helper.Meta'
    type: object
  users.RegisterUserInput:
    properties:
      email:
        type: string
      full_name:
        type: string
      occupation:
        type: string
      password:
        type: string
    required:
    - email
    - full_name
    - occupation
    - password
    type: object
info:
  contact: {}
paths:
  /users:
    post:
      consumes:
      - application/json
      description: This endpoint allows you to register a new user.
      parameters:
      - description: User registration data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/users.RegisterUserInput'
      produces:
      - application/json
      responses:
        "201":
          description: Your account has been created
          schema:
            $ref: '#/definitions/helper.Response'
        "422":
          description: Validation errors
          schema:
            $ref: '#/definitions/helper.Response'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/helper.Response'
      summary: Register a new user
      tags:
      - Users
swagger: "2.0"
